#Kishan Patel - 260376121
#ECSE 427 - Assignment 2
#Compiler: GCC

pa2_test : pa2_test.o mymalloc.o mymalloc.h
	gcc -g -o pa2_test pa2_test.o mymalloc.o 

pa2_test.o : pa2_test.c mymalloc.h
	gcc -g -c pa2_test.c  

mymalloc.o : mymalloc.c
	gcc -g -c mymalloc.c 

